services:
  - type: web
    name: bot-cargo-automatico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    pythonVersion: "3.9.18"
